# Use MPI and Scalapy to distribute all of MICA workflow to work on multiple nodes

prep.py component \
Read input file and slice into manageable sizes

In [1]:
from MICA.lib import utils

In [2]:
#from IPython import parallel
import ipyparallel as ipp

# Launch an ipython parallel cluster
Run this on hpc node to launch a cluster with mpi engines

In [3]:
#this currently needs to be launched from terminal

#import subprocess 
#We need to launch an ipython parallel cluster

#!ipcluster start --n=4
#subprocess.Popen(['ipcluster','start','--n=4'])
#subprocess.Popen(['ipcluster', 'start', '--engines=MPIEngineSetLauncher', '--log-level', 'DEBUG', '--n=4'])


In [4]:
#!ipcluster start --engines=MPIEngineSetLauncher --log-level DEBUG --n=4 &

In [5]:
# Create a parallel client so that we can use %%px cell magic
# With rc and dview, we can interact between mpi ranks and the thread running this notebook
rc = ipp.Client()
dview = rc[:]
rc.ids

[0, 1, 2, 3]

In [6]:
%%px
#load all necessary libraries onto each rank

from scipy.sparse import csr_matrix
from mpi4py import MPI
import sys
import numba
import pandas as pd
import scanpy as sc
import scipy as sci
import numpy as np
import anndata
import time
from sklearn.decomposition import PCA
import fast_histogram
import logging
logging.basicConfig(level=logging.INFO)
from MICA.lib import utils

In [7]:
%%px
from scalapy import *

In [8]:
%%px
import os
import socket
from mpi4py import MPI
comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()
name = MPI.Get_processor_name()
#sys.stdout.write(
#    "Hello, World! I am process %d of %d on %s.\n" 
#    % (rank, size, name))

print("{host}[{pid}]: {rank}/{size}".format(
    host=socket.gethostname(),
    pid=os.getpid(),
    rank=comm.rank,
    size=comm.size,
))

[stdout:0] noderome203[36079]: 0/4
[stdout:1] noderome203[36080]: 1/4
[stdout:2] noderome203[36081]: 2/4
[stdout:3] noderome203[36082]: 3/4


In [9]:
%%px
#this is a defined elsewhere as a standalone python executable
#we are duplicating here to experiment with format for distrubuted computing
def prep_dist(input_file, out_name, slice_unit):
    """ Preprocess input file to create sliced matrices.

    Reads file into HDF5-format, adds parameters, slices data in file, generates several files with
    different combinations of slices.

    Args:
        input_file (str): path to input text-file
        out_name   (str): common rootname of generated output files
        slice_unit (int): size of each slice of cell data in input text-file
    """
    logging.basicConfig(level=logging.INFO)
    
    #Read in whole file stored in anndata csr format
    adf=utils.read_anndata_file(input_file)
    #if adf==None :
    #    raise Exception("Input file ",input_file," not found.")
        
    print("initial data size=",adf.shape)

    slice_size = int(slice_unit)
    
    #df = pd.HDFStore(df_file)["slice_0"]
    
    #compute number of slices needed to break dataset in to slice_size row blocks
    b = int(np.ceil(float(adf.shape[0]) / float(slice_size)))
    #determine how many digits are in b so we can pad spaces for the string output
    digit = int(np.floor(np.log10(b)) + 1)
    #loop over slice numbers
    for i in range(b):
        #slice name is equal to batch index
        slice_name = str(i).zfill(digit)
        #compute batch row indices
        start = i * slice_size
        end = np.min([(i + 1) * slice_size, adf.shape[0]])
        #copy slice to array of slices
        adf_sub=adf[start:end,:]
        #write to file so we don't have to keep each slice in memory
        output_file_name = out_name + ".slice_" + slice_name +".h5ad"
        print("output_file_name: ",output_file_name)
        adf_sub.write(output_file_name)
        
    #return nrows and nslices
    return adf.shape[0], adf.shape[1], b
    


In [10]:
%%px
#ceb create csr version of numba_histogram2d, also compute_bin with knowledge that minx will always be zero

@numba.jit(nopython=True)
def numba_nan_fill(x):
    shape = x.shape
    x = x.ravel()
    x[np.isnan(x)] = 0.0
    x = x.reshape(shape)
    return x

@numba.jit(nopython=True)
def numba_inf_fill(x):
    shape = x.shape
    x = x.ravel()
    x[np.isinf(x)] = 0.0
    x = x.reshape(shape)
    return x

@numba.jit(nopython=True, fastmath=True)
def compute_bin_upperbound(x, max, num_bins):
    """ Compute bin index for a give number.
        Assume that min is always zero
    """
    # special case to mirror NumPy behavior for last bin
    if x == max:
        return num_bins - 1 # a_max always in last bin

    bin = int(num_bins * x / max)

    if bin >= num_bins:
        return None
    else:
        return bin

@numba.jit(nopython=True, fastmath=True)
def numba_histogram2d_csr(arr1, cols1, arr2, cols2, ncols, num_bins):
    """ Compute the bi-dimensional histogram of two data samples.
    Args:
        arr1 (array_like, shape (N,)): An array containing the x coordinates of the points to be histogrammed.
        arr2 (array_like, shape (N,)): An array containing the y coordinates of the points to be histogrammed.
        num_bins (int): int
    Return:
        hist (2D ndarray)
    """
    #for csr arrays we have to compute zero bins ahead of time 
        
    bin_indices1 = np.zeros((ncols,), dtype=np.int16)
    max1 = arr1.max()
    #note that bin_indices has same size/indices as full array x and y
    for i, x in enumerate(arr1.flat):
        #assume zero min
        bin_indices1[cols1[i]] = compute_bin_upperbound(x, max1, num_bins)

    bin_indices2 = np.zeros((ncols,), dtype=np.int16)
    max2 = arr2.max()
    for i, y in enumerate(arr2.flat):
        #assume zero min
        bin_indices2[cols2[i]] = compute_bin_upperbound(y, max2, num_bins)

    hist = np.zeros((num_bins, num_bins), dtype=np.int16)
    for i, b in enumerate(bin_indices1):
        hist[b, bin_indices2[i]] += 1
        
    return hist

In [11]:
%%px
#import numba
@numba.jit(nopython=True, fastmath=True)
def numba_calc_mi_dis_csr(arr1, cols1, arr2, cols2, bins, m):
    """ Calculates a mutual information distance D(X, Y) = H(X, Y) - I(X, Y) using bin-based method

    It takes gene expression data from single cells, and compares them using standard calculation for
    mutual information and joint entropy. It builds a 2d histogram, which is used to calculate P(arr1, arr2).

    Args:
        arr1 (float) nparray of csr: gene expression data for cell 1
        cols1 (int): column indices for csr arr1
        arr2 (float) nparray of csr: gene expression data for cell 2
        cols2 (int): column indices for csr arr
        bins           (int): number of bins
        m              (int): number of genes
    Returns:
        a float between 0 and 1
    """
    hist = numba_histogram2d_csr(arr1, cols1, arr2, cols2, m, bins)
    
    sm = np.sum(hist, axis=1)
    tm = np.sum(hist, axis=0)
    sm = sm / float(sm.sum())
    tm = tm / float(tm.sum())

    sm_tm = np.zeros((bins, bins), dtype=np.float32)
    for i, s in enumerate(sm):
        for j, t in enumerate(tm):
            sm_tm[i, j] = s * t

    fq = hist / float(m)
    div = np.true_divide(fq, sm_tm)
    numba_nan_fill(div)
    ent = np.log(div)
    numba_inf_fill(ent)
    agg = np.multiply(fq, ent)
    #joint_ent = -np.multiply(fq, numba_inf_fill(np.log(fq))).sum()
    #return joint_ent - agg.sum()
    return agg.sum()

In [12]:
%%px
#numba compilation cannot interpret the creation of a 2d array inside of this function so we pass in and out SM_block instead of returning it
#import numba
@numba.jit(nopython=True, fastmath=True)
def process_matrices(Arows,Amat_data,Amat_indptr,Amat_indices,
                     Brows,Bmat_data,Bmat_indptr,Bmat_indices,
                     num_bins,num_genes,
                     SM_block, symmetric=False):
    #(mat1.n_obs,mat1.X.data,mat1.X.indptr,mat1.X.indices, mat2.n_obs,mat2.X.data,mat2.X.indptr,mat2.X.indices,SM,num_bins,mat2.n_vars,symmetric)

    #Arows = mat1.n_obs
    #Brows = mat2.n_obs
    #num_genes = mat1.n_vars
    
    #SM_block = np.ndarray(shape=(Arows,Brows))#, dtype=float, order='F')
    #SM_block = SM_block.reshape(Arows,Brows)
    for i in range(Arows):
        Arowstart = Amat_indptr[i]
        Arowend   = Amat_indptr[i+1]
        Arow_cols = Amat_indices[Arowstart:Arowend]
        Arow_data = Amat_data[Arowstart:Arowend]

        Bstart=0
        Bend=Brows
        #if(symmetric):Bstart=i #upper triangluar
        if(symmetric):Bend=i+1 #lower triangular
        for j in range(Bstart,Bend): 
            Browstart = Bmat_indptr[j]
            Browend   = Bmat_indptr[j+1]
            Brow_cols = Bmat_indices[Browstart:Browend]
            Brow_data = Bmat_data[Browstart:Browend]               
            SM_block[i,j] = numba_calc_mi_dis_csr(Arow_data, Arow_cols, Brow_data, Brow_cols, num_bins, num_genes)
            #SM_block[i*Arows+j] = numba_calc_mi_dis_csr(Arow_data, Arow_cols, Brow_data, Brow_cols, num_bins, num_genes)

            
    return #SM_block


In [13]:
%%px
#from mpi4py import MPI
from scipy.sparse import csr_matrix
#import sys
import pandas as pd

#create a 2d list to hold blocks of similarity matrix
#this should be a global var
#SM = [[None for j in range(b)] for i in range(b)] 

def calc_distance_metric_distributed(in_file_path, project_name, nrows, ncols, nslices, SM):
    
    """ Prepares the already sliced input file for further calculation in MICA.
    Enters pairs of slices (matrices) into temporary HDF5-format files. It enters them
    individually, using their unique key. It also enters the parameter data for every single 
    pair into the key "params", which consists of: [key1, key2, num_bins, num_genes,
    pair_index, project_name, num_slices]
    Args:
        in_file      (str): path to sliced HDF5-format file
        project_name (str): project name used to generate path for final outputs
        nrows : number of rows in global matrix
        ncols : number of vars in global matrix
    """

    
    #create a 2d list to hold blocks of similarity matrix
    #this should be a global var
    #SM = [[None for j in range(b)] for i in range(b)] 
    
    
    #input file is full input that has been segmented into b blocks of rows
    
    #nranks would ideally be equal to  b(b+1)/2
    comm = MPI.COMM_WORLD
    size = comm.Get_size()
    myrank = comm.Get_rank()
    name = MPI.Get_processor_name()
    #sys.stdout.write("Hello, World! I am process %d of %d on %s.\n" % (myrank, size, name))
    
    #in_ = pd.HDFStore(in_file, "r")  # slice.h5
    #b = int(np.ceil(float(nrows) / float(slice_size)))
    digit = int(np.floor(np.log10(nslices)) + 1)

    num_bins = int(np.floor(nrows ** (1 / 3.0)))  # number of bins
    #print("bins= ",bins)
    #b = in_["attr"].loc["slice", 0]  # number of sliced matrix
    b = nslices #number of row blocks (cells)
    m = ncols  # number of cols per row (genes)

    n_block_comparisons = int((b * (b + 1)) / 2)  # total number of row block comparisons needed to compute entire global similarity matrix
    n_jobs_per_rank = n_block_comparisons/size
    if (myrank == 0): print("block comparsons = %d. jobs per rank = %d\n" % (n_block_comparisons, n_jobs_per_rank))

    #build list of row block comparisons that current mpi rank will process
    myslices=[]
    for i in range(b):
        for j in range(i,b): # j in range [i,b]
            idx = int(i * b + j - (i * (i + 1)) / 2)
            targetrank = idx//n_jobs_per_rank
            if (targetrank == myrank): myslices.append((i,j))            

    #from list just generated, only do work assigned to your rank
    for index, tuple in enumerate(myslices):
        #print("tuple=",tuple)
        i=tuple[0] #block row
        j=tuple[1] #block col      

        #get 1st slice (row block) file
        slice_name = str(i).zfill(digit)
        ##ceb we only want to read this once per i,j combination
        input_file = in_file_path + project_name + ".slice_" + slice_name +".h5ad"
        #print("infile seg1: ",input_file)
        mat1 = utils.read_anndata_file(input_file)
    

        #get 2nd slice (row block) file
        slice_name = str(j).zfill(digit)
        input_file = in_file_path + project_name + ".slice_" + slice_name +".h5ad"
        #print("infile seg2: ",input_file)
        mat2 = utils.read_anndata_file(input_file)    

        #check to see if block comparison will result in a symmetric SM matrix
        # so that we can reduce the number of computations in half
        symmetric=False
        if i==j: symmetric=True
        
        print("rank: ",myrank," comparison between segs:",i," x ",j," symmetric=",symmetric)
            
        #compute distance metrics between row blocks
        
        Arows = mat1.n_obs
        Brows = mat2.n_obs
        num_genes = mat1.n_vars #we will assume Acols==Bcols==num_genes
        
        #need SM for each block pair    
        #creates local array of zeros and assigns to global 2d list
        #create matrix of zeros with row order indexing
        SM[i][j] = np.zeros(shape=(Arows,Brows), dtype = float, order = 'C')
 
        #This numba function cannot create a numpy array internally so we return SM[i,j] as a variable
        process_matrices(mat1.n_obs,mat1.X.data,mat1.X.indptr,mat1.X.indices, 
                         mat2.n_obs,mat2.X.data,mat2.X.indptr,mat2.X.indices,
                         num_bins, num_genes, SM[i][j],
                         symmetric #if i==j we can eliminate half of computations
                        )

        #convert to csr
        #we may want to assign this to scalapack distributed matrix here
        #SM[i][j]=csr_matrix(SM[i][j])

    return

In [14]:
%%px
import os
cwd=os.getcwd()
if rank==0:
    print(cwd)
    
data_file_path = cwd+'/test_data/inputs/10x/PBMC/3k/pre-processed/'
input_file_name = data_file_path + 'pbmc3k_preprocessed.h5ad'
project_name = 'pbmc3k'
output_file_name = data_file_path+project_name



[stdout:0] /research/rgs01/home/clusterHome/cburdysh/MICA_Project/MICA_distributed/MICA


In [15]:
%%px
#set slice size (max size of row blocks)
slice_size = 500

In [16]:
%%px
if rank==0:
    print (input_file_name)

[stdout:0] /research/rgs01/home/clusterHome/cburdysh/MICA_Project/MICA_distributed/MICA/test_data/inputs/10x/PBMC/3k/pre-processed/pbmc3k_preprocessed.h5ad


## Run Prep_dist() to split file into slices

In [17]:
%%px
#Run prep.py only on one processor to create the slice files

g_nrows=0 #global number of rows (cells)
ncols=0
nslices=0
if rank==0: 
    #for some unknown reason, running the prep_dist defined in MICA.utils stalls here, although they are identical
    g_nrows, ncols, nslices = prep_dist(input_file_name, output_file_name, slice_size)
    
# this uses the iparallel dview object to distribute these variables from the notebook thread to all mpi ranks
# but the ranks can't communicate back to the notebook thread
#dview.push(dict(nrows=nrows, ncols=ncols, nslices=nslices))

#broadcast resultant variables from root to the other ranks
g_nrows = comm.bcast(g_nrows, root=0)
ncols = comm.bcast(ncols, root=0)
nslices = comm.bcast(nslices, root=0)

[stdout:0] 
initial data size= (2496, 10499)
output_file_name:  /research/rgs01/home/clusterHome/cburdysh/MICA_Project/MICA_distributed/MICA/test_data/inputs/10x/PBMC/3k/pre-processed/pbmc3k.slice_0.h5ad
output_file_name:  /research/rgs01/home/clusterHome/cburdysh/MICA_Project/MICA_distributed/MICA/test_data/inputs/10x/PBMC/3k/pre-processed/pbmc3k.slice_1.h5ad
output_file_name:  /research/rgs01/home/clusterHome/cburdysh/MICA_Project/MICA_distributed/MICA/test_data/inputs/10x/PBMC/3k/pre-processed/pbmc3k.slice_2.h5ad
output_file_name:  /research/rgs01/home/clusterHome/cburdysh/MICA_Project/MICA_distributed/MICA/test_data/inputs/10x/PBMC/3k/pre-processed/pbmc3k.slice_3.h5ad
output_file_name:  /research/rgs01/home/clusterHome/cburdysh/MICA_Project/MICA_distributed/MICA/test_data/inputs/10x/PBMC/3k/pre-processed/pbmc3k.slice_4.h5ad


[stderr:0] 
/home/cburdysh/.conda/envs/py36/lib/python3.6/site-packages/anndata/_core/anndata.py:1094: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  if not is_categorical(df_full[k]):
/home/cburdysh/.conda/envs/py36/lib/python3.6/site-packages/anndata/_core/anndata.py:1192: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  if is_string_dtype(df[key]) and not is_categorical(df[key])


In [20]:
%%px
if rank==0:
    print("global nrows, ncols, slices: ",g_nrows, ncols, nslices)

[stdout:0] global nrows, ncols, slices:  2496 10499 5


## Read in anndata preprocessed files (in distributed mode, by node number) and calculate distance metrics between all row pairs


In [21]:
%%px
#create a 2d list to hold blocks of similarity matrix
#this should be stored in a distributed scalapack matrix
b=nslices #row blocks
SM = [[None for j in range(b)] for i in range(b)] 

start = time.time()
calc_distance_metric_distributed(data_file_path, project_name, g_nrows, ncols, nslices, SM)
end = time.time()
print("Elapsed = %s" % (end - start))


[stdout:0] 
block comparsons = 15. jobs per rank = 3

rank:  0  comparison between segs: 0  x  0  symmetric= True
rank:  0  comparison between segs: 0  x  1  symmetric= False
rank:  0  comparison between segs: 0  x  2  symmetric= False
rank:  0  comparison between segs: 0  x  3  symmetric= False
Elapsed = 27.025275945663452
[stdout:1] 
rank:  1  comparison between segs: 0  x  4  symmetric= False
rank:  1  comparison between segs: 1  x  1  symmetric= True
rank:  1  comparison between segs: 1  x  2  symmetric= False
rank:  1  comparison between segs: 1  x  3  symmetric= False
Elapsed = 26.987526178359985
[stdout:2] 
rank:  2  comparison between segs: 1  x  4  symmetric= False
rank:  2  comparison between segs: 2  x  2  symmetric= True
rank:  2  comparison between segs: 2  x  3  symmetric= False
rank:  2  comparison between segs: 2  x  4  symmetric= False
Elapsed = 27.067891359329224
[stdout:3] 
rank:  3  comparison between segs: 3  x  3  symmetric= True
rank:  3  comparison between segs:

## Create distributed matrix for scalapack and copy distributed blocks into object

In [28]:
%%px 
#from scipy.sparse import csr_matrix #may not use csr as it complicates copy to distributed scalapack and is not used in scalapack apparently
import collections
##lr=[range(5)]
##lc=[range(5)]
for i in range(b):
    for j in range(i,b): # j in range [i,b]
        if isinstance(SM[i][j], collections.Iterable):
            #lm=SM[i][j]#.ravel()
            #B=csr_matrix(SM[0][0]) 
            #print("Rank:",rank, " SM[",i,"][",j,"] nnz=",SM[i][j].getnnz)
            print("Rank:",rank, " SM[",i,"][",j,"]=",SM[i][j])
            print("Rank:",rank, " SM[",i,"][",j,"] size=",np.shape(SM[i][j]))

[stdout:0] 
Rank: 0  SM[ 0 ][ 0 ]= [[0.33805914 0.         0.         ... 0.         0.         0.        ]
 [0.066332   0.45212405 0.         ... 0.         0.         0.        ]
 [0.05676848 0.06047588 0.39173321 ... 0.         0.         0.        ]
 ...
 [0.07054255 0.08004723 0.06371855 ... 0.40356913 0.         0.        ]
 [0.0512154  0.05524977 0.04704487 ... 0.05568945 0.28595673 0.        ]
 [0.05874435 0.06618731 0.05463269 ... 0.06344674 0.04428717 0.32672655]]
Rank: 0  SM[ 0 ][ 0 ] size= (500, 500)
Rank: 0  SM[ 0 ][ 1 ]= [[0.06175365 0.05988961 0.06091765 ... 0.05264516 0.06151162 0.06741739]
 [0.07463322 0.06648138 0.06281537 ... 0.05555061 0.0630906  0.07098869]
 [0.05996313 0.08546759 0.05180793 ... 0.08038354 0.05908661 0.05553384]
 ...
 [0.06945782 0.06715911 0.06659123 ... 0.05521862 0.06859925 0.06996816]
 [0.04923181 0.04707469 0.04850244 ... 0.04421112 0.05931689 0.05210484]
 [0.06143369 0.05605142 0.05415353 ... 0.05311433 0.05567422 0.05471078]]
Rank: 0  SM[ 0 

## Populate a global array with all of the MI data from each rank

Preferably, we would like each rank to contribute of their block MI matrices to the global matrix,
but currently the distributed global matrix has to be constructed from a global (not distributed) array

First, each rank loads it's matrix contribution into a global block matrix, \
And then we use MPI to transfer these contributions to rank 0 from all other ranks.

In [25]:
#We may be able to have each rank copy their data directly to the distributed global matrix (that we have yet to initialize) 
#so that we can avoid having to agglomerate matrix data on a single rank
#dA = dA.np2self(local_a, srow, scol, rank=0)

In [31]:
%%px
#copy SM[i][j] from each rank to root rank 0
n_jobs_per_rank= (int((b * (b + 1)) / 2))/comm.Get_size()
import collections
for i in range(b):
    for j in range(i,b): # j in range [i,b]
        idx = int(i * b + j - (i * (i + 1)) / 2)
        srank = idx//n_jobs_per_rank
        if rank!=0 and isinstance(SM[i][j], collections.Iterable):
            #print("send[",i,j,"] tag: ",idx)
            comm.send(SM[i][j],dest=0,tag=idx)
        elif rank==0 and not isinstance(SM[i][j], collections.Iterable):
            #MB=np.zeros(shape=(Arows,Brows), dtype = float, order = 'C')
            MB=comm.recv( source=srank, tag=idx)
            SM[i][j]=MB
            #print("recv[",i,j,"] tag: ",idx," shape: ",MB.shape, SM[i][j])
            

[stdout:0] 
recv[ 0 4 ] tag:  4  shape:  (500, 496) [[0.06847511 0.07097353 0.03970045 ... 0.05752099 0.04267657 0.0668972 ]
 [0.07487861 0.08324064 0.03985439 ... 0.06336014 0.04781611 0.06866279]
 [0.05921373 0.06319516 0.03860612 ... 0.05280795 0.04746441 0.05657429]
 ...
 [0.07337022 0.08141929 0.04501544 ... 0.06437086 0.04758679 0.07150667]
 [0.05424045 0.05598563 0.04197506 ... 0.06030926 0.04726073 0.04963261]
 [0.05990425 0.06294921 0.03835283 ... 0.04903976 0.03910835 0.0537745 ]]
recv[ 1 1 ] tag:  5  shape:  (500, 500) [[0.36926112 0.         0.         ... 0.         0.         0.        ]
 [0.0649967  0.47480536 0.         ... 0.         0.         0.        ]
 [0.05946971 0.05546087 0.2805864  ... 0.         0.         0.        ]
 ...
 [0.05562528 0.08562544 0.04675215 ... 0.35546833 0.         0.        ]
 [0.05763337 0.0595012  0.06285615 ... 0.05431594 0.37590516 0.        ]
 [0.0664442  0.06006738 0.06291901 ... 0.04923544 0.06159119 0.33837848]]
recv[ 1 2 ] tag:  6 

In [33]:
#%%px
###lr=[range(4)]
###lc=[range(4)]
####Check to see of data was transferred to rank 0
#if rank==0:
#    for i in range(b):
#            for j in range(i,b): # j in range [i,b]
#                #print("SM[",i,j,"] ",np.shape(SM[i][i]))
#                print("SM[",i,j,"] ",SM[i][j])
##                print( (SM[i][j])[lr,lc] )   

In [24]:
#%%px
#from inspect import getmembers, isfunction, ismodule
#if rank == 0:
#    print([o[0] for o in getmembers(scalapy) if ismodule(o[1])])

In [25]:
#%%px
#from inspect import getmembers, isfunction, ismodule
#import scalapy
#if rank==0:
#    print(getmembers(scalapy.blacs, isfunction))
#    #print(getmembers(scalapy.routines, isfunction))

In [26]:
#%%px
#total number of global blocks = total number of block comparisons
#Should be greater than number of ranks to improve load balancing
# b is number of slices (blocks of rows) original data has been discretized into.
#The size of these blocks can be variable
#global_number_of_matrix_blocks= int((b * (b + 1)) / 2) 

#We'll use a 2d process grid to distribute blocks so we want to have num_ranks divisivle by 2

In [27]:
#bcast SM[i][j] from each rank to root rank 0 so that we can load global matrix array


## Convert array into distributed block cyclic global matrix
Simply load a numpy vector with data from each block matrix to use in scalapak distributed matrix initialization

In [34]:
%%px
import collections

#create global 2d array to store MI info which will be sent to create block cyclic distributed matrix
#I would like to know how to create this matrix without having to have the memory of a global array on each rank

#the following two functions are part of the scalapy blockcyclic.py file
#possibly use readmatrix, if we can write out in correct format
#mpi_readmatrix(fname, comm, gshape, dtype, blocksize, process_grid, order='F', displacement=0)

#We can write out local arrays with the following function, and hopefully this creates a distributed matrix file we can read back in
#without having to gather all of the data on a single rank
#To do this we need to create a process grid
#def mpi_writematrix(fname, local_array, comm, gshape, dtype, blocksize, process_grid, order='F', displacement=0):

global_MI=np.zeros([g_nrows,g_nrows])
#global_diag=np.zeros([g_nrows,2]) #add a second col so we can do scalapack matrix ops on it
global_diag=np.zeros([g_nrows,g_nrows]) #add a second col so we can do scalapack matrix ops on it

blocksize=slice_size
if rank==0:
    #load rank data into global matrix
    for i in range(b):
        for j in range(i,b): # j in range [i,b]
            #if SM[i][j]!=None:
            if isinstance(SM[i][j], collections.Iterable):
                lA = SM[i][j]
                print( "rank=",rank,"loading SM[",i,",",j," shape=",np.shape(lA) )
                lr=np.shape(lA)[0]
                lc=np.shape(lA)[1]
                for ii in range(lr):
                    for jj in range(lc):
                        global_MI[i*blocksize+ii, j*blocksize+jj] = lA[ii,jj]
                        #for now we will also store symmetric upper triangular part
                        global_MI[j*blocksize+jj, i*blocksize+ii] = lA[ii,jj]

                        if i==j and ii==jj: 
                            #global_diag[i*blocksize+ii,0]=lA[ii,jj]
                            #global_diag[i*blocksize+ii,0]=lA[ii,jj]
                            global_diag[0,j*blocksize+jj]=lA[ii,jj]
                            

[stdout:0] 
rank= 0 loading SM[ 0 , 0  shape= (500, 500)
rank= 0 loading SM[ 0 , 1  shape= (500, 500)
rank= 0 loading SM[ 0 , 2  shape= (500, 500)
rank= 0 loading SM[ 0 , 3  shape= (500, 500)
rank= 0 loading SM[ 0 , 4  shape= (500, 496)
rank= 0 loading SM[ 1 , 1  shape= (500, 500)
rank= 0 loading SM[ 1 , 2  shape= (500, 500)
rank= 0 loading SM[ 1 , 3  shape= (500, 500)
rank= 0 loading SM[ 1 , 4  shape= (500, 496)
rank= 0 loading SM[ 2 , 2  shape= (500, 500)
rank= 0 loading SM[ 2 , 3  shape= (500, 500)
rank= 0 loading SM[ 2 , 4  shape= (500, 496)
rank= 0 loading SM[ 3 , 3  shape= (500, 500)
rank= 0 loading SM[ 3 , 4  shape= (500, 496)
rank= 0 loading SM[ 4 , 4  shape= (496, 496)


In [35]:
%%px
from scalapy import blacs
import os
import numpy as np
import scipy.linalg as la
from mpi4py import MPI
from scalapy import core
import scalapy.routines as rt

#distribute MI components to ranks as scalapack distributed matrix
comm = MPI.COMM_WORLD
rank = comm.rank
size = comm.size #total number of ranks

global_num_rows =g_nrows
global_num_cols =g_nrows
local_num_rows =g_nrows/b

block_size=64 #default is 32

#Define process grid with process rows and process cols
#We'll use a 2d process grid to distribute blocks so we want to have num_ranks divisible by 2
assert((size % 2)==0)
#ideally we would like BR and BC to the square root of the num_ranks to get a square process matrix
PR=int(np.sqrt(size))
PC=PR

#if we can't create a square matrix, get next best dimensions
if PR*PR!=size:
    PC=size//PR
if rank==0:
    print("PR=",PR, "PC=",PC)

#create mpi comm context to send to blacs communicator    
#process context
#do I need this?
#cntxt = blacs.sys2blacs_handle(comm)
#initialize a process grid to distribute matrix blocks to.
#blacs.gridinit(ctxt,order='R',BR,BC)
#blacs.gridinit(pc,order='R',BR,BC)
#core.initmpi([PR, PC], block_shape=[local_num_rows,local_num_rows])
#instead of creating a global array on every processor, we want to load a 
#global array with local data
#MI=core.DistributedMatrix(global_shape=[global_num_rows,global_num_cols])


core.initmpi([PR, PC],block_shape=[block_size,block_size])

#convert to fortran array indexing to match scalapack functions
global_MI=np.asfortranarray(global_MI)
#create global matrix from array on rank0
dMI=core.DistributedMatrix.from_global_array(global_MI,rank=0)

#Array must be 2D, so this fails
#convert to fortran array indexing to match scalapack functions
#global_diag=np.asfortranarray(global_diag)
#create global matrix from array on rank0
#dMI_diag=core.DistributedMatrix.from_global_array(global_diag,rank=0)




#blacs.gridinit(ctxt, b, b)
#ranklist = [(0, 0), 
#            (0, 1), (1, 1),
#            (0, 2), (1, 2), (2, 2),
#            (0, 3), (1, 3), (2, 3), (3, 3),
#            (0, 4), (1, 4), (2, 4), (3, 4), (4, 4)
#           ]

[stdout:0] PR= 2 PC= 2


In [36]:
%%px
mi_filename = data_file_path+project_name+'_mi_distributed.scalapack'
dMI.to_file(mi_filename)

In [93]:
#%%px
#mi_filename = data_file_path+project_name+'_mi_distributed.scalapack'
#dMI.from_file(mi_filename, global_shape=[g_nrows,g_nrows], dtype=np.float64, block_shape=[block_size,block_size])

In [37]:
#%%px
#if rank==0: 
#    print ('rank %d has global_shape of dMI = %s' % (rank, dMI.global_shape))
#print ('rank %d has local_shape of dMI = %s' % (rank, dMI.local_shape))
#print ('rank %d has block_shape of dMI = %s' % (rank, dMI.block_shape))
#print(dMI.local_array)

In [38]:
%%px
#Array must be 2D for this to work
#convert to fortran array indexing to match scalapack functions
global_diag=np.asfortranarray(global_diag)
#create global matrix from array on rank0
dMI_diag=core.DistributedMatrix.from_global_array(global_diag,rank=0)

In [39]:
#%%px
#if rank==0: 
#    print ('rank %d has global_shape of dMI_diag = %s' % (rank, dMI_diag.global_shape))
#print ('rank %d has local_shape of dMI_diag = %s' % (rank, dMI_diag.local_shape))
#print ('rank %d has block_shape of dMI_diag = %s' % (rank, dMI_diag.block_shape))
##print(dMI_diag.local_array)

In [40]:
#%%px
#dMI_diag_T=dMI_diag.T
#if rank==0: 
#    print ('rank %d has global_shape of dMI_diag = %s' % (rank, dMI_diag_T.global_shape))
#print ('rank %d has local_shape of dMI_diag = %s' % (rank, dMI_diag_T.local_shape))
#print ('rank %d has block_shape of dMI_diag = %s' % (rank, dMI_diag_T.block_shape))
#
#print(dMI_diag_T.local_array)

## Use scalapack to compute distributed GEMM

In [41]:
%%px
import scalapy.routines as rt
#dMI_norm=dMI_diag.T*dMI_diag
dMI_norm = rt.dot(dMI_diag,dMI_diag,transA='T')


In [42]:
#%%px
#if rank==0: 
#    print ('rank %d has global_shape of dMI_diag = %s' % (rank, dMI_norm.global_shape))
#print ('rank %d has local_shape of dMI_diag = %s' % (rank, dMI_norm.local_shape))
#print ('rank %d has block_shape of dMI_diag = %s' % (rank, dMI_norm.block_shape))
#print(dMI_norm.local_array)

In [43]:
%%px
#compute sqrt of each element
dMI_norm_square=core.DistributedMatrix.empty_like(dMI)
dMI_norm_square.local_array[:] = np.sqrt(dMI_norm.local_array[:])

In [44]:
#%%px
#if rank==0: 
#    print ('rank %d has global_shape of dMI_diag = %s' % (rank, dMI_norm_square.global_shape))
#print ('rank %d has local_shape of dMI_diag = %s' % (rank, dMI_norm_square.local_shape))
#print ('rank %d has block_shape of dMI_diag = %s' % (rank, dMI_norm_square.block_shape))
#print(dMI_norm_square.local_array)

In [45]:
%%px
dMI_normed=core.DistributedMatrix.empty_like(dMI)
dMI_normed.local_array[:] = dMI.local_array[:] / dMI_norm_square.local_array[:]

In [46]:
%%px
if rank==0: 
    print ('rank %d has global_shape of dMI_diag = %s' % (rank, dMI_normed.global_shape))
print ('rank %d has local_shape of dMI_diag = %s' % (rank, dMI_normed.local_shape))
print ('rank %d has block_shape of dMI_diag = %s' % (rank, dMI_normed.block_shape))
print(dMI_normed.local_array)

[stdout:0] 
rank 0 has global_shape of dMI_diag = (2496, 2496)
rank 0 has local_shape of dMI_diag = (1280, 1280)
rank 0 has block_shape of dMI_diag = (64, 64)
[[1.         0.16966721 0.15599682 ... 0.18526718 0.15847534 0.20418114]
 [0.16966721 1.         0.14370048 ... 0.17646388 0.15353732 0.18121605]
 [0.15599682 0.14370048 1.         ... 0.15800564 0.16373497 0.16040872]
 ...
 [0.18526718 0.17646388 0.15800564 ... 1.         0.2063892  0.19392593]
 [0.15847534 0.15353732 0.16373497 ... 0.2063892  1.         0.17301498]
 [0.20418114 0.18121605 0.16040872 ... 0.19392593 0.17301498 1.        ]]
[stdout:1] 
rank 1 has local_shape of dMI_diag = (1280, 1216)
rank 1 has block_shape of dMI_diag = (64, 64)
[[0.13344376 0.15981576 0.15132607 ... 0.14577705 0.19038733 0.18626778]
 [0.14142939 0.16082045 0.14256036 ... 0.15681292 0.1834772  0.17961762]
 [0.12705919 0.13859349 0.14067777 ... 0.19254956 0.15870398 0.16179771]
 ...
 [0.13176611 0.15744818 0.13899435 ... 0.15545719 0.18048995 0.18

In [47]:
%%px
mi_normed_filename = data_file_path+project_name+'_mi_normed_distributed.scalapack'
dMI_normed.to_file(mi_normed_filename)

## Now compute eigenvalues and eigenvectors of dissimmilarity matrix

In [ ]:
def mds(in_mat_file, max_dim, out_file_name, perplexity=30, print_plot="True", dist_method="mi",):
    hdf = pd.HDFStore(in_mat_file)
    if dist_method == "mi":
        dlplf = 1 - hdf["norm_mi"]
    elif dist_method == "euclidean":
        df = hdf[dist_method]
    else:
        df = 1 - hdf[dist_method]

    hdf.close()
    n = df.shape[0]
    H = np.eye(n) - np.ones((n, n)) / n
    B = -H.dot(df ** 2).dot(H) / 2
    evals, evecs = eigh(B, eigvals=(n - np.min([n, 200]), n - 1))
    
    idx = np.argsort(evals)[::-1]
    evals = evals[idx]
    evecs = evecs[:, idx]
    evals_pos = evals > 0
    L = np.diag(np.sqrt(evals[evals_pos]))
    V = evecs[:, evals_pos]
    Y = pd.DataFrame(
        data=V.dot(L),
        index=df.index,
        columns=["mds_" + str(x) for x in np.arange(1, L.shape[0] + 1)],
    )

    Y.to_hdf(out_file_name + "_reduced.h5", "mds")  # save reduced mi in mds

    if print_plot == "True":
        vis = tsne(
            Y,
            max_dim,
            out_file_name,
            "mds",
            perplexity,
            print_plot,
        )
        vis.to_hdf(out_file_name + "_reduced", "mds_tsne")  # save preview in key "mds_tsne"

In [48]:
%%px
import scalapy.routines as rt

n= g_nrows

#convert similarity matrix to dissimilarity matrix
#df= 1-df
MDS= core.DistributedMatrix.empty_like(dMI)
MDS.local_array[:]=1.0-dMI_normed.local_array[:]

# H = I-Ones/n
I= core.DistributedMatrix.identity(n=g_nrows)
Ones= core.DistributedMatrix.empty_like(dMI)
Ones.local_array[:]=1.0/n
H = core.DistributedMatrix.empty_like(dMI)
H.local_array[:] = I.local_array[:] - Ones.local_array[:]

# B = -H.dot(MDS**2).dot(H)/2
negH= core.DistributedMatrix.empty_like(dMI)
negH.local_array[:]= -H.local_array[:]
MDS2= core.DistributedMatrix.empty_like(dMI)
MDS2.local_array[:] = MDS.local_array[:]**2
C=rt.dot(negH,MDS2)
B = rt.dot(C,H)
B.local_array[:]=B.local_array[:]/2.0
#dMI_norm=dMI_diag.T*dMI_diag
#dMI_norm = rt.dot(dMI_diag,dMI_diag,transA='T')


In [49]:
%%px
if rank==0: 
    print ('rank %d has global_shape of dMI_diag = %s' % (rank, MDS.global_shape))
print ('rank %d has local_shape of dMI_diag = %s' % (rank, MDS.local_shape))
print ('rank %d has block_shape of dMI_diag = %s' % (rank, MDS.block_shape))
print(MDS.local_array)

[stdout:0] 
rank 0 has global_shape of dMI_diag = (2496, 2496)
rank 0 has local_shape of dMI_diag = (1280, 1280)
rank 0 has block_shape of dMI_diag = (64, 64)
[[0.         0.83033279 0.84400318 ... 0.81473282 0.84152466 0.79581886]
 [0.83033279 0.         0.85629952 ... 0.82353612 0.84646268 0.81878395]
 [0.84400318 0.85629952 0.         ... 0.84199436 0.83626503 0.83959128]
 ...
 [0.81473282 0.82353612 0.84199436 ... 0.         0.7936108  0.80607407]
 [0.84152466 0.84646268 0.83626503 ... 0.7936108  0.         0.82698502]
 [0.79581886 0.81878395 0.83959128 ... 0.80607407 0.82698502 0.        ]]
[stdout:1] 
rank 1 has local_shape of dMI_diag = (1280, 1216)
rank 1 has block_shape of dMI_diag = (64, 64)
[[0.86655624 0.84018424 0.84867393 ... 0.85422295 0.80961267 0.81373222]
 [0.85857061 0.83917955 0.85743964 ... 0.84318708 0.8165228  0.82038238]
 [0.87294081 0.86140651 0.85932223 ... 0.80745044 0.84129602 0.83820229]
 ...
 [0.86823389 0.84255182 0.86100565 ... 0.84454281 0.81951005 0.81

In [50]:
%%px
if rank==0: 
    print ('rank %d has global_shape of dMI_diag = %s' % (rank, MDS2.global_shape))
print ('rank %d has local_shape of dMI_diag = %s' % (rank, MDS2.local_shape))
print ('rank %d has block_shape of dMI_diag = %s' % (rank, MDS2.block_shape))
print(MDS2.local_array)

[stdout:0] 
rank 0 has global_shape of dMI_diag = (2496, 2496)
rank 0 has local_shape of dMI_diag = (1280, 1280)
rank 0 has block_shape of dMI_diag = (64, 64)
[[0.         0.68945254 0.71234137 ... 0.66378957 0.70816375 0.63332766]
 [0.68945254 0.         0.73324887 ... 0.67821173 0.71649907 0.67040716]
 [0.71234137 0.73324887 0.         ... 0.7089545  0.6993392  0.70491351]
 ...
 [0.66378957 0.67821173 0.7089545  ... 0.         0.6298181  0.6497554 ]
 [0.70816375 0.71649907 0.6993392  ... 0.6298181  0.         0.68390422]
 [0.63332766 0.67040716 0.70491351 ... 0.6497554  0.68390422 0.        ]]
[stdout:1] 
rank 1 has local_shape of dMI_diag = (1280, 1216)
rank 1 has block_shape of dMI_diag = (64, 64)
[[0.75091973 0.70590956 0.72024745 ... 0.72969685 0.65547268 0.66216012]
 [0.73714349 0.70422232 0.73520274 ... 0.71096445 0.66670948 0.67302724]
 [0.76202567 0.74202118 0.73843469 ... 0.65197621 0.707779   0.70258308]
 ...
 [0.75383009 0.70989358 0.74133073 ... 0.71325257 0.67159672 0.66

In [51]:
%%px
if rank==0: 
    print ('rank %d has global_shape of dMI_diag = %s' % (rank, B.global_shape))
print ('rank %d has local_shape of dMI_diag = %s' % (rank, B.local_shape))
print ('rank %d has block_shape of dMI_diag = %s' % (rank, B.block_shape))
print(B.local_array)

[stdout:0] 
rank 0 has global_shape of dMI_diag = (2496, 2496)
rank 0 has local_shape of dMI_diag = (1280, 1280)
rank 0 has block_shape of dMI_diag = (64, 64)
[[ 3.32606572e-01 -4.48879650e-03 -1.22124044e-02 ... -4.99538265e-04
  -9.33603291e-03  1.19542557e-02]
 [-4.48879650e-03  3.47868371e-01 -1.50352510e-02 ... -7.97225127e-05
  -5.87279447e-03  1.04540298e-03]
 [-1.22124044e-02 -1.50352510e-02  3.55309993e-01 ... -1.17302924e-02
   6.42794877e-03 -1.24869591e-02]
 ...
 [-4.99538265e-04 -7.97225127e-05 -1.17302924e-02 ...  3.30183917e-01
   2.86254621e-02  2.52905849e-03]
 [-9.33603291e-03 -5.87279447e-03  6.42794877e-03 ...  2.86254621e-02
   3.56885108e-01 -1.19475721e-03]
 [ 1.19542557e-02  1.04540298e-03 -1.24869591e-02 ...  2.52905849e-03
  -1.19475721e-03  3.24629599e-01]]
[stdout:1] 
rank 1 has local_shape of dMI_diag = (1280, 1216)
rank 1 has block_shape of dMI_diag = (64, 64)
[[-0.01057509 -0.00223418 -0.00174018 ... -0.01561031  0.00304875
   0.0050489 ]
 [ 0.00394393  0

In [52]:
%%px
import scalapy.routines as rt
#compute eigh(B,)
#we want to pick out the top 200 eigenvalues/vectors from the matrix
#evals, evecs = eigh(B, eigvals=(n - np.min([n, 200]), n - 1))
evals, dZd = rt.eigh(B,overwrite_a=False)
evecs = dZd.to_global_array(rank=0)
#gZd = dZd.to_global_array(rank=0)

In [53]:
%%px
print(evals)

[stdout:0] 
[7.27742329e-16 1.11552126e-01 1.15620174e-01 ... 8.43778466e+00
 1.07555328e+01 2.98340037e+01]
[stdout:1] 
[7.27742329e-16 1.11552126e-01 1.15620174e-01 ... 8.43778466e+00
 1.07555328e+01 2.98340037e+01]
[stdout:2] 
[7.27742329e-16 1.11552126e-01 1.15620174e-01 ... 8.43778466e+00
 1.07555328e+01 2.98340037e+01]
[stdout:3] 
[7.27742329e-16 1.11552126e-01 1.15620174e-01 ... 8.43778466e+00
 1.07555328e+01 2.98340037e+01]


In [ ]:
#%%px
#import scalapy.routines as rt
##obtain dissimilarity matrix
#n= g_nrows
##MDS=1-dMI
#MDS= core.DistributedMatrix.empty_like(dMI)
##MDS.local_array[:]=1.0-dMI.local_Array[:]
#I= core.DistributedMatrix.identity(n=g_nrows)
#Ones= core.DistributedMatrix.empty_like(dMI)
#Ones.local_array[:]=1.0/n
##create arrays
##create identity matrix and then subtract 1/n from all entries
#H= np.eye(n) - np.ones((n, n)) / n
#H= I - Ones
#B= -H.dot(df ** 2).dot(H) / 2
#
##compute eigh(B,)
##we want to pick out the top 200 eigenvalues/vectors from the matrix
##evals, evecs = eigh(B, eigvals=(n - np.min([n, 200]), n - 1))
#evals, dZd = rt.eigh(B,overwrite_a=False)
#evecs = dZd.to_global_array(rank=0)

In [ ]:
#%%px
#dgi, dlri, dlci = diagMI.local_diagonal_indices()

In [ ]:
#%%px
#gi, lri, lci = dMI.local_diagonal_indices()

In [ ]:
#%%px
#diagMI.local_array[lri,0] = dMI.local_array[lri,lci]

In [ ]:
#%%px
#print ('rank %d has local_shape of dMI = %s' % (rank, diagMI.local_shape))
#print ('rank %d has block_shape of dMI = %s' % (rank, diagMI.block_shape))
#print(diagMI.local_array)

In [44]:
#%%px
#diagMI_dot = dot(dMI_diag,dMI_diag,transB='T')
#diagMI_dot = dMI_diag.T * dMI_diag

#diagMI_dot.local_array[lri,lci] = 1.0/np.sqrt(diagMI_dot.local_array[lri,lci])

In [55]:
#%%px
#print(diagMI_dot.local_array)

In [ ]:
#%%px
#print(diagMI_dot.local_array)

In [ ]:
#%%px
#diagMI_normed = dMI*diagMI_dot

In [ ]:
#%%px
#print(dMI_normed.local_array)

In [ ]:
#%%px
##lr=[range(2400,2495)]
##lc=[range(2400,2495)]
#print(len(dMI.local_array[lri,lci]))
#diag=dMI.local_array[lri,lci]
#print(diag)

In [ ]:
#%%px
#dMI_dot=dot(dMI,dMI,transB='T')

In [ ]:
#%%px
#dMI_dot.desc

In [ ]:
#%%px
#dgi, dlri, dlci = dMI_dot.local_diagonal_indices()
#print(dMI_dot.local_array[dlri,dlci])

In [ ]:
#%%px
#Note these values are in mixed order due to block cyclic partition. last rank last block does not correspond to last values in global diagonal
#print(diag)


In [ ]:
%%px
if rank==0:
    print(evals)

In [ ]:
%%px
if rank==0:
    nnzgZd=
    print(len(gZd))
    print(gZd)

In [ ]:
#compute eigenvalues,vectors
#evals1, evecs1 = scalapy.eigh(dMI, overwrite_a=False)

## Write distributed matrix to files